//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.81.0。
// 
namespace TestDemo
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "NciicServicesHttpBinding", Namespace = "https://api.nciic.org.cn/NciicServices")]
    public partial class NciicServices : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback nciicDiscernOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckGetPhoneOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckChinaOperationCompleted;

        private System.Threading.SendOrPostCallback nciicGetConditionOperationCompleted;

        private System.Threading.SendOrPostCallback nciicExactSearchOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCourtOperationCompleted;

        private System.Threading.SendOrPostCallback nciicFmxxEntryOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCombineSearchOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckMobileOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckFileOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckHotelOperationCompleted;

        private System.Threading.SendOrPostCallback nciicKyxxEntryOperationCompleted;

        private System.Threading.SendOrPostCallback nciicBirthplaceCompareOperationCompleted;

        private System.Threading.SendOrPostCallback nciicGetFileOperationCompleted;

        private System.Threading.SendOrPostCallback nciicAddrExactSearchOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckSetPhoneOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCompareOperationCompleted;

        private System.Threading.SendOrPostCallback nciicDateCollectionOperationCompleted;

        private System.Threading.SendOrPostCallback nciicCheckScanOperationCompleted;

        /// <remarks/>
        public NciicServices()
        {
            this.Url = "https://ws.nciic.org.cn/nciic_ws/services/NciicServices";
        }

        /// <remarks/>
        public event nciicDiscernCompletedEventHandler nciicDiscernCompleted;

        /// <remarks/>
        public event nciicCheckGetPhoneCompletedEventHandler nciicCheckGetPhoneCompleted;

        /// <remarks/>
        public event nciicCheckChinaCompletedEventHandler nciicCheckChinaCompleted;

        /// <remarks/>
        public event nciicGetConditionCompletedEventHandler nciicGetConditionCompleted;

        /// <remarks/>
        public event nciicExactSearchCompletedEventHandler nciicExactSearchCompleted;

        /// <remarks/>
        public event nciicCourtCompletedEventHandler nciicCourtCompleted;

        /// <remarks/>
        public event nciicFmxxEntryCompletedEventHandler nciicFmxxEntryCompleted;

        /// <remarks/>
        public event nciicCheckCompletedEventHandler nciicCheckCompleted;

        /// <remarks/>
        public event nciicCombineSearchCompletedEventHandler nciicCombineSearchCompleted;

        /// <remarks/>
        public event nciicCheckMobileCompletedEventHandler nciicCheckMobileCompleted;

        /// <remarks/>
        public event nciicCheckFileCompletedEventHandler nciicCheckFileCompleted;

        /// <remarks/>
        public event nciicCheckHotelCompletedEventHandler nciicCheckHotelCompleted;

        /// <remarks/>
        public event nciicKyxxEntryCompletedEventHandler nciicKyxxEntryCompleted;

        /// <remarks/>
        public event nciicBirthplaceCompareCompletedEventHandler nciicBirthplaceCompareCompleted;

        /// <remarks/>
        public event nciicGetFileCompletedEventHandler nciicGetFileCompleted;

        /// <remarks/>
        public event nciicAddrExactSearchCompletedEventHandler nciicAddrExactSearchCompleted;

        /// <remarks/>
        public event nciicCheckSetPhoneCompletedEventHandler nciicCheckSetPhoneCompleted;

        /// <remarks/>
        public event nciicCompareCompletedEventHandler nciicCompareCompleted;

        /// <remarks/>
        public event nciicDateCollectionCompletedEventHandler nciicDateCollectionCompleted;

        /// <remarks/>
        public event nciicCheckScanCompletedEventHandler nciicCheckScanCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicDiscern([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicDiscern", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicDiscern(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicDiscern", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicDiscern(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicDiscernAsync(string inLicense, string inConditions)
        {
            this.nciicDiscernAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicDiscernAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicDiscernOperationCompleted == null))
            {
                this.nciicDiscernOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicDiscernOperationCompleted);
            }
            this.InvokeAsync("nciicDiscern", new object[] {
                        inLicense,
                        inConditions}, this.nciicDiscernOperationCompleted, userState);
        }

        private void OnnciicDiscernOperationCompleted(object arg)
        {
            if ((this.nciicDiscernCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicDiscernCompleted(this, new nciicDiscernCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public FileObjectSetPhone nciicCheckGetPhone([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string id)
        {
            object[] results = this.Invoke("nciicCheckGetPhone", new object[] {
                        inLicense,
                        id});
            return ((FileObjectSetPhone)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckGetPhone(string inLicense, string id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckGetPhone", new object[] {
                        inLicense,
                        id}, callback, asyncState);
        }

        /// <remarks/>
        public FileObjectSetPhone EndnciicCheckGetPhone(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((FileObjectSetPhone)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckGetPhoneAsync(string inLicense, string id)
        {
            this.nciicCheckGetPhoneAsync(inLicense, id, null);
        }

        /// <remarks/>
        public void nciicCheckGetPhoneAsync(string inLicense, string id, object userState)
        {
            if ((this.nciicCheckGetPhoneOperationCompleted == null))
            {
                this.nciicCheckGetPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckGetPhoneOperationCompleted);
            }
            this.InvokeAsync("nciicCheckGetPhone", new object[] {
                        inLicense,
                        id}, this.nciicCheckGetPhoneOperationCompleted, userState);
        }

        private void OnnciicCheckGetPhoneOperationCompleted(object arg)
        {
            if ((this.nciicCheckGetPhoneCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckGetPhoneCompleted(this, new nciicCheckGetPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheckChina([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCheckChina", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckChina(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckChina", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheckChina(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckChinaAsync(string inLicense, string inConditions)
        {
            this.nciicCheckChinaAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCheckChinaAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCheckChinaOperationCompleted == null))
            {
                this.nciicCheckChinaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckChinaOperationCompleted);
            }
            this.InvokeAsync("nciicCheckChina", new object[] {
                        inLicense,
                        inConditions}, this.nciicCheckChinaOperationCompleted, userState);
        }

        private void OnnciicCheckChinaOperationCompleted(object arg)
        {
            if ((this.nciicCheckChinaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckChinaCompleted(this, new nciicCheckChinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicGetCondition([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense)
        {
            object[] results = this.Invoke("nciicGetCondition", new object[] {
                        inLicense});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicGetCondition(string inLicense, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicGetCondition", new object[] {
                        inLicense}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicGetCondition(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicGetConditionAsync(string inLicense)
        {
            this.nciicGetConditionAsync(inLicense, null);
        }

        /// <remarks/>
        public void nciicGetConditionAsync(string inLicense, object userState)
        {
            if ((this.nciicGetConditionOperationCompleted == null))
            {
                this.nciicGetConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicGetConditionOperationCompleted);
            }
            this.InvokeAsync("nciicGetCondition", new object[] {
                        inLicense}, this.nciicGetConditionOperationCompleted, userState);
        }

        private void OnnciicGetConditionOperationCompleted(object arg)
        {
            if ((this.nciicGetConditionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicGetConditionCompleted(this, new nciicGetConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicExactSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicExactSearch", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicExactSearch(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicExactSearch", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicExactSearch(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicExactSearchAsync(string inLicense, string inConditions)
        {
            this.nciicExactSearchAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicExactSearchAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicExactSearchOperationCompleted == null))
            {
                this.nciicExactSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicExactSearchOperationCompleted);
            }
            this.InvokeAsync("nciicExactSearch", new object[] {
                        inLicense,
                        inConditions}, this.nciicExactSearchOperationCompleted, userState);
        }

        private void OnnciicExactSearchOperationCompleted(object arg)
        {
            if ((this.nciicExactSearchCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicExactSearchCompleted(this, new nciicExactSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCourt([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCourt", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCourt(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCourt", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCourt(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCourtAsync(string inLicense, string inConditions)
        {
            this.nciicCourtAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCourtAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCourtOperationCompleted == null))
            {
                this.nciicCourtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCourtOperationCompleted);
            }
            this.InvokeAsync("nciicCourt", new object[] {
                        inLicense,
                        inConditions}, this.nciicCourtOperationCompleted, userState);
        }

        private void OnnciicCourtOperationCompleted(object arg)
        {
            if ((this.nciicCourtCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCourtCompleted(this, new nciicCourtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicFmxxEntry([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicFmxxEntry", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicFmxxEntry(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicFmxxEntry", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicFmxxEntry(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicFmxxEntryAsync(string inLicense, string inConditions)
        {
            this.nciicFmxxEntryAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicFmxxEntryAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicFmxxEntryOperationCompleted == null))
            {
                this.nciicFmxxEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicFmxxEntryOperationCompleted);
            }
            this.InvokeAsync("nciicFmxxEntry", new object[] {
                        inLicense,
                        inConditions}, this.nciicFmxxEntryOperationCompleted, userState);
        }

        private void OnnciicFmxxEntryOperationCompleted(object arg)
        {
            if ((this.nciicFmxxEntryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicFmxxEntryCompleted(this, new nciicFmxxEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheck([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCheck", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheck(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheck", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheck(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckAsync(string inLicense, string inConditions)
        {
            this.nciicCheckAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCheckAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCheckOperationCompleted == null))
            {
                this.nciicCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckOperationCompleted);
            }
            this.InvokeAsync("nciicCheck", new object[] {
                        inLicense,
                        inConditions}, this.nciicCheckOperationCompleted, userState);
        }

        private void OnnciicCheckOperationCompleted(object arg)
        {
            if ((this.nciicCheckCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckCompleted(this, new nciicCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCombineSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCombineSearch", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCombineSearch(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCombineSearch", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCombineSearch(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCombineSearchAsync(string inLicense, string inConditions)
        {
            this.nciicCombineSearchAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCombineSearchAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCombineSearchOperationCompleted == null))
            {
                this.nciicCombineSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCombineSearchOperationCompleted);
            }
            this.InvokeAsync("nciicCombineSearch", new object[] {
                        inLicense,
                        inConditions}, this.nciicCombineSearchOperationCompleted, userState);
        }

        private void OnnciicCombineSearchOperationCompleted(object arg)
        {
            if ((this.nciicCombineSearchCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCombineSearchCompleted(this, new nciicCombineSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheckMobile([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCheckMobile", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckMobile(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckMobile", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheckMobile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckMobileAsync(string inLicense, string inConditions)
        {
            this.nciicCheckMobileAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCheckMobileAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCheckMobileOperationCompleted == null))
            {
                this.nciicCheckMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckMobileOperationCompleted);
            }
            this.InvokeAsync("nciicCheckMobile", new object[] {
                        inLicense,
                        inConditions}, this.nciicCheckMobileOperationCompleted, userState);
        }

        private void OnnciicCheckMobileOperationCompleted(object arg)
        {
            if ((this.nciicCheckMobileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckMobileCompleted(this, new nciicCheckMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheckFile([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] FileObject fileObject)
        {
            object[] results = this.Invoke("nciicCheckFile", new object[] {
                        fileObject});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckFile(FileObject fileObject, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckFile", new object[] {
                        fileObject}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheckFile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckFileAsync(FileObject fileObject)
        {
            this.nciicCheckFileAsync(fileObject, null);
        }

        /// <remarks/>
        public void nciicCheckFileAsync(FileObject fileObject, object userState)
        {
            if ((this.nciicCheckFileOperationCompleted == null))
            {
                this.nciicCheckFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckFileOperationCompleted);
            }
            this.InvokeAsync("nciicCheckFile", new object[] {
                        fileObject}, this.nciicCheckFileOperationCompleted, userState);
        }

        private void OnnciicCheckFileOperationCompleted(object arg)
        {
            if ((this.nciicCheckFileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckFileCompleted(this, new nciicCheckFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheckHotel([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCheckHotel", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckHotel(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckHotel", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheckHotel(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckHotelAsync(string inLicense, string inConditions)
        {
            this.nciicCheckHotelAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCheckHotelAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCheckHotelOperationCompleted == null))
            {
                this.nciicCheckHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckHotelOperationCompleted);
            }
            this.InvokeAsync("nciicCheckHotel", new object[] {
                        inLicense,
                        inConditions}, this.nciicCheckHotelOperationCompleted, userState);
        }

        private void OnnciicCheckHotelOperationCompleted(object arg)
        {
            if ((this.nciicCheckHotelCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckHotelCompleted(this, new nciicCheckHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicKyxxEntry([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicKyxxEntry", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicKyxxEntry(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicKyxxEntry", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicKyxxEntry(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicKyxxEntryAsync(string inLicense, string inConditions)
        {
            this.nciicKyxxEntryAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicKyxxEntryAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicKyxxEntryOperationCompleted == null))
            {
                this.nciicKyxxEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicKyxxEntryOperationCompleted);
            }
            this.InvokeAsync("nciicKyxxEntry", new object[] {
                        inLicense,
                        inConditions}, this.nciicKyxxEntryOperationCompleted, userState);
        }

        private void OnnciicKyxxEntryOperationCompleted(object arg)
        {
            if ((this.nciicKyxxEntryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicKyxxEntryCompleted(this, new nciicKyxxEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicBirthplaceCompare([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicBirthplaceCompare", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicBirthplaceCompare(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicBirthplaceCompare", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicBirthplaceCompare(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicBirthplaceCompareAsync(string inLicense, string inConditions)
        {
            this.nciicBirthplaceCompareAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicBirthplaceCompareAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicBirthplaceCompareOperationCompleted == null))
            {
                this.nciicBirthplaceCompareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicBirthplaceCompareOperationCompleted);
            }
            this.InvokeAsync("nciicBirthplaceCompare", new object[] {
                        inLicense,
                        inConditions}, this.nciicBirthplaceCompareOperationCompleted, userState);
        }

        private void OnnciicBirthplaceCompareOperationCompleted(object arg)
        {
            if ((this.nciicBirthplaceCompareCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicBirthplaceCompareCompleted(this, new nciicBirthplaceCompareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public FileObject nciicGetFile([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string id)
        {
            object[] results = this.Invoke("nciicGetFile", new object[] {
                        inLicense,
                        id});
            return ((FileObject)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicGetFile(string inLicense, string id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicGetFile", new object[] {
                        inLicense,
                        id}, callback, asyncState);
        }

        /// <remarks/>
        public FileObject EndnciicGetFile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((FileObject)(results[0]));
        }

        /// <remarks/>
        public void nciicGetFileAsync(string inLicense, string id)
        {
            this.nciicGetFileAsync(inLicense, id, null);
        }

        /// <remarks/>
        public void nciicGetFileAsync(string inLicense, string id, object userState)
        {
            if ((this.nciicGetFileOperationCompleted == null))
            {
                this.nciicGetFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicGetFileOperationCompleted);
            }
            this.InvokeAsync("nciicGetFile", new object[] {
                        inLicense,
                        id}, this.nciicGetFileOperationCompleted, userState);
        }

        private void OnnciicGetFileOperationCompleted(object arg)
        {
            if ((this.nciicGetFileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicGetFileCompleted(this, new nciicGetFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicAddrExactSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicAddrExactSearch", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicAddrExactSearch(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicAddrExactSearch", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicAddrExactSearch(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicAddrExactSearchAsync(string inLicense, string inConditions)
        {
            this.nciicAddrExactSearchAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicAddrExactSearchAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicAddrExactSearchOperationCompleted == null))
            {
                this.nciicAddrExactSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicAddrExactSearchOperationCompleted);
            }
            this.InvokeAsync("nciicAddrExactSearch", new object[] {
                        inLicense,
                        inConditions}, this.nciicAddrExactSearchOperationCompleted, userState);
        }

        private void OnnciicAddrExactSearchOperationCompleted(object arg)
        {
            if ((this.nciicAddrExactSearchCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicAddrExactSearchCompleted(this, new nciicAddrExactSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public FileObjectSetPhone nciicCheckSetPhone([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] FileObjectSetPhone fileObject)
        {
            object[] results = this.Invoke("nciicCheckSetPhone", new object[] {
                        fileObject});
            return ((FileObjectSetPhone)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckSetPhone(FileObjectSetPhone fileObject, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckSetPhone", new object[] {
                        fileObject}, callback, asyncState);
        }

        /// <remarks/>
        public FileObjectSetPhone EndnciicCheckSetPhone(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((FileObjectSetPhone)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckSetPhoneAsync(FileObjectSetPhone fileObject)
        {
            this.nciicCheckSetPhoneAsync(fileObject, null);
        }

        /// <remarks/>
        public void nciicCheckSetPhoneAsync(FileObjectSetPhone fileObject, object userState)
        {
            if ((this.nciicCheckSetPhoneOperationCompleted == null))
            {
                this.nciicCheckSetPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckSetPhoneOperationCompleted);
            }
            this.InvokeAsync("nciicCheckSetPhone", new object[] {
                        fileObject}, this.nciicCheckSetPhoneOperationCompleted, userState);
        }

        private void OnnciicCheckSetPhoneOperationCompleted(object arg)
        {
            if ((this.nciicCheckSetPhoneCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckSetPhoneCompleted(this, new nciicCheckSetPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCompare([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicCompare", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCompare(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCompare", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCompare(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCompareAsync(string inLicense, string inConditions)
        {
            this.nciicCompareAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicCompareAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicCompareOperationCompleted == null))
            {
                this.nciicCompareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCompareOperationCompleted);
            }
            this.InvokeAsync("nciicCompare", new object[] {
                        inLicense,
                        inConditions}, this.nciicCompareOperationCompleted, userState);
        }

        private void OnnciicCompareOperationCompleted(object arg)
        {
            if ((this.nciicCompareCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCompareCompleted(this, new nciicCompareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicDateCollection([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions)
        {
            object[] results = this.Invoke("nciicDateCollection", new object[] {
                        inLicense,
                        inConditions});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicDateCollection(string inLicense, string inConditions, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicDateCollection", new object[] {
                        inLicense,
                        inConditions}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicDateCollection(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicDateCollectionAsync(string inLicense, string inConditions)
        {
            this.nciicDateCollectionAsync(inLicense, inConditions, null);
        }

        /// <remarks/>
        public void nciicDateCollectionAsync(string inLicense, string inConditions, object userState)
        {
            if ((this.nciicDateCollectionOperationCompleted == null))
            {
                this.nciicDateCollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicDateCollectionOperationCompleted);
            }
            this.InvokeAsync("nciicDateCollection", new object[] {
                        inLicense,
                        inConditions}, this.nciicDateCollectionOperationCompleted, userState);
        }

        private void OnnciicDateCollectionOperationCompleted(object arg)
        {
            if ((this.nciicDateCollectionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicDateCollectionCompleted(this, new nciicDateCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "https://api.nciic.org.cn/NciicServices", ResponseNamespace = "https://api.nciic.org.cn/NciicServices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string nciicCheckScan([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inLicense, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inConditions, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string inKey)
        {
            object[] results = this.Invoke("nciicCheckScan", new object[] {
                        inLicense,
                        inConditions,
                        inKey});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginnciicCheckScan(string inLicense, string inConditions, string inKey, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("nciicCheckScan", new object[] {
                        inLicense,
                        inConditions,
                        inKey}, callback, asyncState);
        }

        /// <remarks/>
        public string EndnciicCheckScan(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void nciicCheckScanAsync(string inLicense, string inConditions, string inKey)
        {
            this.nciicCheckScanAsync(inLicense, inConditions, inKey, null);
        }

        /// <remarks/>
        public void nciicCheckScanAsync(string inLicense, string inConditions, string inKey, object userState)
        {
            if ((this.nciicCheckScanOperationCompleted == null))
            {
                this.nciicCheckScanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnciicCheckScanOperationCompleted);
            }
            this.InvokeAsync("nciicCheckScan", new object[] {
                        inLicense,
                        inConditions,
                        inKey}, this.nciicCheckScanOperationCompleted, userState);
        }

        private void OnnciicCheckScanOperationCompleted(object arg)
        {
            if ((this.nciicCheckScanCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nciicCheckScanCompleted(this, new nciicCheckScanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://domain.webservices.serv.nciic.com")]
    public partial class FileObjectSetPhone
    {

        private byte[] fileField;

        private string infoField;

        private string licenseField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string license
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://domain.webservices.serv.nciic.com")]
    public partial class FileObject
    {

        private string errField;

        private byte[] fileField;

        private string licenseField;

        private string returnTypeField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string err
        {
            get
            {
                return this.errField;
            }
            set
            {
                this.errField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string license
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string returnType
        {
            get
            {
                return this.returnTypeField;
            }
            set
            {
                this.returnTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicDiscernCompletedEventHandler(object sender, nciicDiscernCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicDiscernCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicDiscernCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckGetPhoneCompletedEventHandler(object sender, nciicCheckGetPhoneCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckGetPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckGetPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public FileObjectSetPhone Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((FileObjectSetPhone)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckChinaCompletedEventHandler(object sender, nciicCheckChinaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckChinaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckChinaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicGetConditionCompletedEventHandler(object sender, nciicGetConditionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicGetConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicGetConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicExactSearchCompletedEventHandler(object sender, nciicExactSearchCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicExactSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicExactSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCourtCompletedEventHandler(object sender, nciicCourtCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCourtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCourtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicFmxxEntryCompletedEventHandler(object sender, nciicFmxxEntryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicFmxxEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicFmxxEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckCompletedEventHandler(object sender, nciicCheckCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCombineSearchCompletedEventHandler(object sender, nciicCombineSearchCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCombineSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCombineSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckMobileCompletedEventHandler(object sender, nciicCheckMobileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckFileCompletedEventHandler(object sender, nciicCheckFileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckHotelCompletedEventHandler(object sender, nciicCheckHotelCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicKyxxEntryCompletedEventHandler(object sender, nciicKyxxEntryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicKyxxEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicKyxxEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicBirthplaceCompareCompletedEventHandler(object sender, nciicBirthplaceCompareCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicBirthplaceCompareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicBirthplaceCompareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicGetFileCompletedEventHandler(object sender, nciicGetFileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicGetFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicGetFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public FileObject Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((FileObject)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicAddrExactSearchCompletedEventHandler(object sender, nciicAddrExactSearchCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicAddrExactSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicAddrExactSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckSetPhoneCompletedEventHandler(object sender, nciicCheckSetPhoneCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckSetPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckSetPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public FileObjectSetPhone Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((FileObjectSetPhone)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCompareCompletedEventHandler(object sender, nciicCompareCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCompareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCompareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicDateCollectionCompletedEventHandler(object sender, nciicDateCollectionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicDateCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicDateCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    public delegate void nciicCheckScanCompletedEventHandler(object sender, nciicCheckScanCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nciicCheckScanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal nciicCheckScanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
