var shares = {
	'default':{
		title:'口袋德州扑克',
		img:'http://cache.poketec.com/pkpoker/images/shares/share_login_icon.png',
		summary:'我发现了一款很好玩的游戏，只要玩牌就能拿话费哦！',
		msg:'风靡世界的德州扑克，聪明人的游戏！智力、勇气、耐心，巅峰对决从此开始！',
		button:'进入游戏',		
	},			
	'playcard':{
		title:'口袋德州扑克',
		img:'http://cache.poketec.com/pkpoker/images/shares/share_playcard_icon.png',
		summary:'我刚在“口袋德州扑克”中,通过“*pType*”,获得了“*chip*”金币。',
		msg:'风靡世界的德州扑克，聪明人的游戏！智力、勇气、耐心，巅峰对决从此开始！',
		button:'进入游戏',
	},
	'level':{
		title:'口袋德州扑克',
		img:'http://cache.poketec.com/pkpoker/images/shares/share_level_icon.png',
		summary:'我刚在“口袋德州扑克”中荣升到*level*级，快来挑战我吧！',
		msg:'风靡世界的德州扑克，聪明人的游戏！智力、勇气、耐心，巅峰对决从此开始！',
		button:'进入游戏',		
	},
	'login':{
		title:'口袋德州扑克',
		img:'http://cache.poketec.com/pkpoker/images/shares/share_login_icon.png',
		summary:'我刚在口袋德州扑克中领取每日登录奖励*chip*游戏币，你快来试试手气',
		msg:'风靡世界的德州扑克，聪明人的游戏！智力、勇气、耐心，巅峰对决从此开始！',
		button:'进入游戏',		
	},	
	'achievem':{
		title:'口袋德州扑克',
		img:'http://cache.poketec.com/pkpoker/images/shares/share_level_icon.png',
		summary:'我刚在“口袋德州扑克”中获得了“*achName*”成就。',
		msg:'风靡世界的德州扑克，聪明人的游戏！智力、勇气、耐心，巅峰对决从此开始！',
		button:'获得成就',		
	}	
};
